<?php

/**
 * @file
 * Contains islandora_access.module.
 */

/**
 * Helper function to get node IDs a user was added to field_administator of.
 */
function islandora_access_get_admins_nids($uid, &$nids, $parent = FALSE, &$visited = []) : void {
  if ($uid == 0) {
    return;
  }

  if ($parent && isset($visited[$parent])) {
    return;
  }

  if ($parent) {
    $visited[$parent] = TRUE;
  }

  $query = \Drupal::database()->select('node__field_administrator', 'a');
  $query->innerJoin('node_field_data', 'n', 'n.nid = a.entity_id');
  $query->condition('field_administrator_target_id', $uid);

  if ($parent) {
    $query->innerJoin('node__field_member_of', 'm', 'm.field_member_of_target_id = :nid', [':nid' => $parent]);
    $query->condition('m.entity_id', $parent, '<>');
    $query->fields('m', ['entity_id']);
    $query->groupBy('m.entity_id');
  }
  else {
    $query->fields('n', ['nid']);
    $query->groupBy('n.nid');
  }

  $ids = $query->execute()->fetchCol();
  foreach ($ids as $nid) {
    $nids[$nid] = $nid;
    if (islandora_access_node_is_collection($nid)) {
      islandora_access_get_admins_nids($uid, $nids, $nid, $visited);
    }
  }
}

/**
 * Helper function to detect collections.
 *
 * @param int $nid
 *   The node ID.
 *
 * @return bool
 *   TRUE if the node is a collection, FALSE otherwise.
 */
function islandora_access_node_is_collection(int $nid, bool $includeCompoundObjects = TRUE) : bool {
  $query = \Drupal::database()->select('node__field_model', 'nm');
  $query->innerJoin('taxonomy_term__field_external_uri', 'te', 'te.entity_id = nm.field_model_target_id');
  $query->fields('te', ['field_external_uri_uri']);
  $query->condition('nm.entity_id', $nid);
  $query->condition('nm.deleted', 0);
  $model_uri = $query->execute()
    ->fetchField();

  if (!$model_uri) {
    return FALSE;
  }

  if ($model_uri === 'http://purl.org/dc/dcmitype/Collection') {
    return TRUE;
  }

  if ($includeCompoundObjects && $model_uri === 'http://vocab.getty.edu/aat/300242735') {
    return TRUE;
  }

  return FALSE;

}
