<?php

/**
 * @file
 * Contains islandora_access.module.
 */

use Drupal\node\Entity\Node;
use Drupal\node\NodeInterface;

/**
 * Helper function to get node IDs a user was added to field_administator of.
 */
function islandora_access_get_admins_nids($uid, &$nids, $parent = FALSE, &$visited = []) {
  if ($uid == 0) {
    return;
  }

  if ($parent && isset($visited[$parent])) {
    return;
  }

  if ($parent) {
    $visited[$parent] = TRUE;
  }

  $query = $db->select('node__field_administrator', 'a');
  $query->innerJoin('node_field_data', 'n', 'n.nid = a.entity_id');
  $query->condition('field_administrator_target_id', $uid);

  if ($parent) {
    $query->innerJoin('node__field_member_of', 'm', 'm.field_member_of_target_id = :nid', [':nid' => $parent]);
    $query->condition('m.entity_id', $parent, '<>');
    $query->fields('m', ['entity_id']);
    $query->groupBy('m.entity_id');
  }
  else {
    $query->fields('n', ['nid']);
    $query->groupBy('n.nid');
  }

  $ids = $query->execute()->fetchCol();
  foreach ($ids as $nid) {
    $node = Node::load($nid);
    $nids[$nid] = $nid;
    if (islandora_access_node_is_collection($node)) {
      islandora_access_get_admins_nids($uid, $nids, $nid, $visited);
    }
  }
}

/**
 * Helper function to detect collections.
 */
function islandora_access_node_is_collection(NodeInterface $node, $includeCompoundObjects = TRUE) : bool {
  if (!$node->hasField('field_model') || $node->field_model->isEmpty()) {
    return FALSE;
  }

  if (is_null($node->field_model->entity) || !$node->field_model->entity->hasField('field_external_uri') || $node->field_model->entity->field_external_uri->isEmpty()) {
    return FALSE;
  }

  if ($node->field_model->entity->field_external_uri->uri === 'http://purl.org/dc/dcmitype/Collection') {
    return TRUE;
  }

  if ($includeCompoundObjects && $node->field_model->entity->field_external_uri->uri === 'http://vocab.getty.edu/aat/300242735') {
    return TRUE;
  }

  return FALSE;
}
